### ISSUE TITLE
Group Custom Link form components together

### ISSUE THREAD

**Issue by cplkake** [chriskthomas/linkfree-generator#17]
I think the form would be a little more user-friendly if the components for the custom links were grouped together. As things are, here is what they look like:

![Screen Shot 2023-07-02 at 4 47 08 PM](https://github.com/chriskthomas/linkfree-generator/assets/42398320/1c38ce58-95e8-4aa0-948c-43744e26a225)

I propose grouping them together to look something like this:

![Screen Shot 2023-07-02 at 4 50 08 PM](https://github.com/chriskthomas/linkfree-generator/assets/42398320/4cb7c1f9-2c08-4dd7-b3b1-157c1eac54f3)

**Comment by chriskthomas** [comment]
That looks good. Can you submit a pull request?

**Comment by mwt** [comment]
Related to #14

**Comment by cplkake** [comment]
This wouldn't be related to the theme styling issue tho, would it? This is a proposed fix for the form itself, not a linkfree theme
