### ISSUE TITLE
Implement the "Add Custom Link" button in js

### ISSUE THREAD

**Issue by chriskthomas** [chriskthomas/linkfree-generator#2]
Right now, the "Add Custom Link" button is processed by reloading the page with a `?n=` query string that sets the number of custom icon fields to display.

This works. However, pressing the button will reset all of the information that the user has entered into the form. A better solution would be to add the custom icon fields using JavaScript in the frontend so that we do not have this issue.

**Comment by CharanMN7** [comment]
This can totally be done in the JavaScript in the frontend right when the page loads. It looks like you used a counting variable to create unique IDs, and the index for the custom links IDs starts from 5. This changes if you add or remove any links above this section. So, we can use a custom attribute to send this index as data from the PHP backend using which the JavaScript can handle it!
I'll fork and make a pull request for this feature. Do consider assigning me to the issue.

**Comment by chriskthomas** [comment]
Hi. Sounds good! I'm looking forward to reviewing it!

**Comment by CharanMN7** [comment]
I've completed porting the feature to the Frontend. It no longer refreshes to add an extra field. Plus, I tested everything locally to make sure everything was working fine. Here is the link to the pull request: #7
