### ISSUE TITLE
Update README.md To Link The Docs

### ISSUE THREAD

**Issue by Adedoyin-Emmanuel** [chriskthomas/linkfree-generator#22]
Update README.md to link to the `docs` folder so users can read the docs on how to deploy their generated index.html files

**Comment by chriskthomas** [comment]
Sure. I intend to also generate a docs site at some point. I want to include previews of all the themes.

**Comment by chriskthomas** [comment]
Thanks @Adedoyin-Emmanuel

Part of that docs site I mentioned is now up. You can preview themes here:
https://chriskthomas.github.io/linkfree-themes/

**Comment by Adedoyin-Emmanuel** [comment]
You are welcome,  I would check it out ❤️
