### ISSUE TITLE
Allow users to submit links without typing https://

### ISSUE THREAD

**Issue by hoon610** [chriskthomas/linkfree-generator#27]
Hi I think it would be a little more user friendly if you could add links without including the https://. Going to work on this by adding JavaScript validation if thats ok

**Comment by chriskthomas** [comment]
Ok. I think you should add a blur event that will add the protocol if the user omits it.

**Comment by mwt** [comment]
> Ok. I think you should add a blur event that will add the protocol if the user omits it.

Yeah, you could just append "https://" on blur if the validity check fails.

**Comment by hoon610** [comment]
Ok. I was making the pull request for the validation and didn't see this. I'll try it with the blur event tomorrow

**Comment by hoon610** [comment]
Did not mean to press close with comment
