### ISSUE TITLE
Link to docs

### ISSUE THREAD

**Issue by chriskthomas** [chriskthomas/linkfree-generator#36]
Add a link on [`src/index.php`](https://github.com/chriskthomas/linkfree-generator/edit/main/src/index.php) to the docs. The url for the documentation is:

https://chriskthomas.github.io/linkfree-generator/

**Comment by coderight1** [comment]
Hi @chriskthomas , i am willing to resolve this issue but i am not completely able to understand where i need to add documentation url , i think it should at the footer of the page, please correct me, if i am wrong and kindly explain the requirements.

**Comment by chriskthomas** [comment]
And now it's on the main version!

**Comment by coderight1** [comment]
Thank you, @chriskthomas.

I have started the repository and am eager to contribute to this project if I am able to.
