### ISSUE TITLE
[Enhancement]: Improve the home page frontend

### ISSUE THREAD

**Issue by rajmanna-dev** [chriskthomas/linkfree-generator#50]
Right now the homepage is not looking user-friendly at all.
I would love to contribute, if this project still maintained then please assing me and don't forget to add hacktoberfest label on it.

**Comment by chriskthomas** [comment]
The hacktoberfest label has been on this repository for a long time because it is sponsored by DigitalOcean, which also sponsors hacktoberfest.

What specifically do you think is not user-friendly on the homepage and what do you want to do to fix it?

**Comment by rajmanna-dev** [comment]
I want to improve overall styling/appearance of the home page.

Mostly using CSS.

**Comment by chriskthomas** [comment]
Ok. Feel free to submit a PR.
